name: Upload to Anaconda

on:
  workflow_call:
    secrets:
      ANACONDA_USER:
        required: true
      ANACONDA_PASS:
        required: true

jobs:
  anaconda_upload:
    name: Upload to Anaconda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-output

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.8'

      - name: install anaconda client
        run: pip install anaconda-client anaconda-auth

      - name: publish-to-anaconda
        continue-on-error: true
        run: |
          anaconda login \
              --at anaconda.org \
              --username ${{ secrets.ANACONDA_USER }} \
              --password "${{ secrets.ANACONDA_PASS }}"
          cd wheels
          for FILE in *
          do
            if echo "$FILE" | grep -qi "android"; then
              LABEL="android"
            else
              LABEL="ios"
            fi
            anaconda upload --force --label "$LABEL" "$FILE"
          done

      - name: anaconda logout
        run: anaconda logout --at anaconda.org
